[versions]
composeUi = "1.11.4"
coroutines = "1.11.0"
junit = "4.13.2"

[libraries]
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeUi" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
